INFRA-259   Fix the jenkinsfile for hygiene to fail if we get an ERROR:

diff --git a/etc/process/Jenkinsfile-hygiene b/etc/process/Jenkinsfile-hygiene
--- a/etc/process/Jenkinsfile-hygiene
+++ b/etc/process/Jenkinsfile-hygiene
@@ -192,21 +192,25 @@ pipeline {
             $(grep -r 'utl-av[:;.]Release' ./fibo | sed 's/:.*$//;s/^/--data=/' | grep -F ".rdf") \
             --query=./fibo/etc/testing/echo.sq \
             --results=TTL > ./target/PROD.ttl
-
+	  
           echo "Running tests"
           echo "Errors in DEV"
           echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-          find ./fibo/etc \
-            -name 'testHygiene*.sq' \
-            -exec grep "banner" {} \\; \
-            -exec ./jena/bin/arq --data=./target/DEV.ttl --query={} \\; | sed 's/PRODERROR/WARN/'
-          echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-          echo "Errors in PROD"
-          echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
-          find ./fibo/etc \
-            -name 'testHygiene*.sq' \
-            -exec grep "banner" {} \\; \
-            -exec ./jena/bin/arq --data=./target/PROD.ttl --query={} \\; | sed 's/PRODERROR/ERROR/'
+          (
+              find ./fibo/etc \
+		  -name 'testHygiene*.sq' \
+		  -exec grep "banner" {} \\; \
+		  -exec ./jena/bin/arq --data=./target/DEV.ttl --query={} \\; | sed 's/PRODERROR/WARN/'
+	   ) 2>&1 |  grep -z "ERROR:" && exit 1 
+           echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+           echo "Errors in PROD"
+           echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
+           (
+	       find ./fibo/etc \
+		   -name 'testHygiene*.sq' \
+		   -exec grep "banner" {} \\; \
+		   -exec ./jena/bin/arq --data=./target/PROD.ttl --query={} \\; | sed 's/PRODERROR/ERROR/'
+	    ) 2>&1 |  grep -z "ERROR:" && exit 1 
           echo "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
         '''
         archiveArtifacts artifacts: 'target/*.ttl', fingerprint: true
