INFRA-194 Merged job config into Jenkinsfile

diff --git a/etc/process/Jenkinsfile b/etc/process/Jenkinsfile
--- a/etc/process/Jenkinsfile
+++ b/etc/process/Jenkinsfile
@@ -7,17 +7,20 @@
 //
 // See https://jenkins.io/doc/book/pipeline/jenkinsfile/
 //
+
+properties([
+    buildDiscarder(
+        logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')
+    ),
+    pipelineTriggers([])
+])
+
+GIT_BRANCH = ""
+GIT_TAG_NAME = ""
+
 stage('Prepare') {
-
-    properties([
-        buildDiscarder(
-            logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')
-        ),
-        pipelineTriggers([])
-    ])
-
     //
-    // Run on the stardog node
+    // Run the prepare stage on the stardog node, check out all the repos there
     //
     // NOTE: For now it' the stardog node since we have more processing power there and there are things
     // installed there that we don't have on the jenkins master (such as "nix.sh")
@@ -30,6 +33,27 @@ stage('Prepare') {
             checkout scm
             echo 'Checked out fibo repo'
             sh 'ls -al'
+            dir('etc/process') {
+                stash includes: 'fibo-copy-to-site.sh', name: 'fibo-copy-to-site-script'
+            }
+            GIT_BRANCH = sh returnStdout: true, script: 'git rev-parse --abbrev-ref HEAD'
+            //
+            // Replace all slashes in a branch name with dashes so that we don't mess up the URLs for the ontologies
+            //
+            GIT_BRANCH = GIT_BRANCH.trim().toLowerCase()
+            echo "GIT_BRANCH=${GIT_BRANCH}"
+
+            GIT_BRANCH = GIT_BRANCH.replaceAll('\\\\', '-')
+            echo "GIT_BRANCH=${GIT_BRANCH}"
+            //
+            // Get the git tag name if the current commit points is pointed to by a tag
+            //
+            GIT_TAG_NAME = sh returnStdout: true, script: 'set +e ; git describe --contains 2>/dev/null | exit 0'
+            GIT_TAG_NAME = GIT_TAG_NAME.trim()
+            if (GIT_TAG_NAME?.trim()) {
+                GIT_TAG_NAME = "latest"
+            }
+            echo "GIT_TAG_NAME=${GIT_TAG_NAME}"
         }
         //
         // Then check out the fibo-infra repo content into the ./fibo-infra directory
@@ -42,6 +66,10 @@ stage('Prepare') {
             //
             git credentialsId: 'edmcjenkins_at_edmcouncil.org', url: 'git@github.com:edmcouncil/fibo-infra.git'
             echo 'Checked out fibo-infra repo'
+            //
+            // Stash the nomagic templates so that they can be unstashed on the nomagix box
+            //
+            stash includes: 'magicdraw/Concept Modeler/**', name: 'nomagic-templates'
         }
         //
         // Then check out the LCC repo into the ./LCC directory
@@ -77,7 +105,8 @@ stage('Build') {
             // TODO: Split this script up in separate "stages" in this repository
             //
             dir('fibo-infra') {
-                sh './jenkins/bin/publish-fibo.sh'
+                echo "Execute the publish-fibo.sh script:"
+                sh "set -x ; export GIT_BRANCH=${GIT_BRANCH} ; export GIT_TAG_NAME=${GIT_TAG_NAME} ; ./jenkins/bin/publish-fibo.sh"
             }
             //
             // Archive the artifacts
@@ -94,78 +123,124 @@ stage('Build') {
     //
     "nomagic" : {
         node('nomagic') {
+            unstash 'nomagic-templates'
             echo "Executing generate script on the nomagic box"
-            sh """#!/bin/bash -x
+            //
+            // Copy the nomagic templates (as they are stored in the fibo-infra repo)
+            // to the right location
+            //
+            dir('magicdraw/Concept Modeler') {
+                sh 'pwd'
+                sh 'find .'
+                sh 'cp -vr . /home/ec2-user/MagicDraw/data/defaults/data/reports/Concept\\ Modeler/'
+            }
 
-                export DISPLAY=localhost:10.0
-                whoami
-                pwd
+            sh """
+                |#!/bin/bash -x
+                |
+                |export DISPLAY=localhost:10.0
+                |whoami
+                |pwd
+                |
+                |#/home/ec2-user/dev.sh
+                |/home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/generate.sh \\
+                |    -login "EDMCJenkins" \\
+                |    -server "twc184.nomagic.com:3579" \\
+                |    -password "hZ7LQF_kmFV-6N2E" \\
+                |    -project "FIBO-Master" \\
+                |    -template "Natural Language Glossary" \\
+                |    -package "Release;Provisional;Informative" \\
+                |    -output "DEVELOPMENT.html" \\
+                |    -servertype "twcloud" \\
+                |    -report "Default Development FIBO"
+                |rc=\$?
+                |echo rc=\${rc}
+                |
+                |#/home/ec2-user/prod.sh
+                |/home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/generate.sh \\
+                |    -login "EDMCJenkins" \\
+                |    -server "twc184.nomagic.com:3579" \\
+                |    -password "hZ7LQF_kmFV-6N2E" \\
+                |    -project "FIBO-Master" \\
+                |    -template "Natural Language Glossary" \\
+                |    -package "Release" \\
+                |    -output "PRODUCTION.html" \\
+                |    -servertype "twcloud" \\
+                |    -report "Default Production FIBO"
+                |rc=\$?
+                |echo rc=\${rc}
+                |
+                |cp /home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/*.html .
+                |
+                |cp -r /home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/resources .
+                |
+                |sed -i DEVELOPMENT.html -e 's!<br>!<br/>!g'
+                |sed -i PRODUCTION.html -e 's!<br>!<br/>!g'
+                |
+                |sed -e '/<script /,/<\\/script>/d' DEVELOPMENT.html > DEVIN.html
+                |sed -e '/<script /,/<\\/script>/d' PRODUCTION.html > PRODIN.html
+                |
+                |chmod a+x  ~/workspace/NoMagic/fibo-publish-nomagic/bin/SaxonHE9-8-0-4J/*.jar
+                |
+                |java \\
+                |    -cp ~/workspace/NoMagic/fibo-publish-nomagic/bin/SaxonHE9-8-0-4J/saxon9he.jar \\
+                |    net.sf.saxon.Transform \\
+                |    -o:datadictionaryDEV.csv \\
+                |    -xsl:./jenkins/bin/glossary-to-csv.xsl \\
+                |    DEVIN.html
+                |java \\
+                |    -cp ~/workspace/NoMagic/fibo-publish-nomagic/bin/SaxonHE9-8-0-4J/saxon9he.jar \\
+                |    net.sf.saxon.Transform \\
+                |    -o:datadictionaryPROD.csv \\
+                |    -xsl:./jenkins/bin/glossary-to-csv.xsl \\
+                |    PRODIN.html
+                |
+                |#cat /home/ec2-user/dev.sh
+                |#cat /home/ec2-user/prod.sh
+                |cat /home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/generate.sh
+                |
+                |#exit 0
+                |## Below this line is the code that JG put there as an alternative to the above (newer) code
+                |
+                |#unset DISPLAY
+                |
+                |#if ! cd /home/ec2-user/MagicDraw ; then
+                |#    echo "Could not find MagicDraw directory"
+                |#    exit 1
+                |#fi
+                |#if ! cd ./plugins/com.nomagic.magicdraw.reportwizard ; then
+                |#    echo "Could not find MagicDraw report wizard"
+                |#    exit 1
+                |#fi
+                |
+                |#./generate.sh \\
+                |#    -login "EDMCJenkins" \\
+                |#    -server "twc184.nomagic.com:3579" \\
+                |#    -password "hZ7LQF_kmFV-6N2E" \\
+                |#    -project "FIBO-Master" \\
+                |#    -template "Natural Language Glossary for FIBO versions" \\
+                |#    -package "Release;Provisional;Informative" \\
+                |#    -output "${WORKSPACE}/development.html" \\
+                |#    -servertype "twcloud" \\
+                |#    -report "Development"
+                |
+                |#./generate.sh \\
+                |#    -login "EDMCJenkins" \\
+                |#    -server "twc184.nomagic.com:3579" \\
+                |#    -password "hZ7LQF_kmFV-6N2E" \\
+                |#    -project "FIBO-Master" \\
+                |#    -template "Natural Language Glossary for FIBO versions" \\
+                |#    -package "Release" \\
+                |#    -output "${WORKSPACE}/production.html" \\
+                |#    -servertype "twcloud" \\
+                |#    -report "Production"
+            """.stripMargin('|')
 
-                # JG>DA, what's happening here??
-                #cp -r \
-                #  "~/workspace/NoMagic/fibo-publish-nomagic/magicdraw/Concept Modeler/*" \
-                #  "~/MagicDraw/data/defaults/data/reports/Concept Modeler/"
-
-                /home/ec2-user/dev.sh
-                /home/ec2-user/prod.sh
-
-                cp /home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/*.html .
-
-                cp -r /home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/resources .
-
-                sed -i DEVELOPMENT.html -e 's!<br>!<br/>!g'
-                sed -i PRODUCTION.html -e 's!<br>!<br/>!g'
-
-                sed -e '/<script /,/<\\/script>/d' DEVELOPMENT.html > DEVIN.html
-                sed -e '/<script /,/<\\/script>/d' PRODUCTION.html > PRODIN.html
-
-                chmod a+x  ~/workspace/NoMagic/fibo-publish-nomagic/bin/SaxonHE9-8-0-4J/*.jar
-
-                java -cp ~/workspace/NoMagic/fibo-publish-nomagic/bin/SaxonHE9-8-0-4J/saxon9he.jar net.sf.saxon.Transform -o:datadictionaryDEV.csv -xsl:./jenkins/bin/glossary-to-csv.xsl DEVIN.html
-                java -cp ~/workspace/NoMagic/fibo-publish-nomagic/bin/SaxonHE9-8-0-4J/saxon9he.jar net.sf.saxon.Transform -o:datadictionaryPROD.csv -xsl:./jenkins/bin/glossary-to-csv.xsl PRODIN.html
-
-                cat /home/ec2-user/dev.sh
-                cat /home/ec2-user/prod.sh
-                cat /home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/generate.sh
-
-                exit 0
-                # Below this line is the code that JG put there as an alternative to the above (newer) code
-
-                unset DISPLAY
-
-                if ! cd /home/ec2-user/MagicDraw ; then
-                    echo "Could not find MagicDraw directory"
-                    exit 1
-                fi
-                if ! cd ./plugins/com.nomagic.magicdraw.reportwizard ; then
-                    echo "Could not find MagicDraw report wizard"
-                    exit 1
-                fi
-
-                ./generate.sh \
-                    -login "EDMCJenkins" \
-                    -server "twc184.nomagic.com:3579" \
-                    -password "hZ7LQF_kmFV-6N2E" \
-                    -project "FIBO-Master" \
-                    -template "Natural Language Glossary for FIBO versions" \
-                    -package "Release;Provisional;Informative" \
-                    -output "${WORKSPACE}/development.html" \
-                    -servertype "twcloud" \
-                    -report "Development"
-
-                ./generate.sh \
-                    -login "EDMCJenkins" \
-                    -server "twc184.nomagic.com:3579" \
-                    -password "hZ7LQF_kmFV-6N2E" \
-                    -project "FIBO-Master" \
-                    -template "Natural Language Glossary for FIBO versions" \
-                    -package "Release" \
-                    -output "${WORKSPACE}/production.html" \
-                    -servertype "twcloud" \
-                    -report "Production"
-
-            """
-            stash includes: '*.html', name: 'nomagic-output'
+            //
+            // Now publish the artifacts generated in this stage to the Jenkins master so that they can be unstashed
+            // from there into the next stage.
+            //
+            stash includes: '*.html, *.csv', name: 'nomagic-output'
         }
     }
 }
@@ -181,20 +256,15 @@ stage('Publish') {
     //
     node('stardog') {
 
-        echo 'Unstashing fibo-publish-script artifacts:'
-        sh 'ls -al'
-        unstash 'fibo-publish-script'
-        sh 'ls -al'
-
-        echo 'Unstashing nomagic output:'
-        unstash 'nomagic-output'
-        sh 'ls -al'
-
         dir('target') {
+
+            echo 'Unstashing nomagic output:'
+            unstash 'nomagic-output'
             sh 'ls -al'
-            sh 'find .'
-            sh 'cp -r generated fibo'
-            sh 'cp *.html fibo/glossary'
+
+            unstash 'fibo-copy-to-site-script'
+            sh './fibo-copy-to-site.sh'
+
             sh 'ls -al /mnt/jenkins-disk/spec.edmcouncil.org/'
             sh 'cp -vr . /mnt/jenkins-disk/spec.edmcouncil.org/'
         }
