INFRA-194 Fix nomagic task?

diff --git a/etc/process/Jenkinsfile b/etc/process/Jenkinsfile
--- a/etc/process/Jenkinsfile
+++ b/etc/process/Jenkinsfile
@@ -69,37 +69,69 @@ stage('Build') {
     // NOTE: For now it' the stardog node since we have more processing power there and there are things
     // installed there that we don't have on the jenkins master (such as "nix.sh")
     //
-    node('stardog') {
-        //
-        // Execute the publish script
-        //
-        // TODO: Split this script up in separate "stages" in this repository
-        //
-        dir('fibo-infra') {
-            sh './jenkins/bin/publish-fibo.sh'
+    parallel "publish-script" : {
+        node('stardog') {
+            //
+            // Execute the publish script
+            //
+            // TODO: Split this script up in separate "stages" in this repository
+            //
+            dir('fibo-infra') {
+                sh './jenkins/bin/publish-fibo.sh'
+            }
+            //
+            // Archive the artifacts
+            //
+            //archiveArtifacts artifacts: 'target/**', fingerprint: true, onlyIfSuccessful: true
+            //
+            // Also via stash. If this works, the archiveArtifacts line abpve is not needed
+            //
+            stash includes: 'target/**', name: 'fibo-publish-script'
         }
-        //
-        // Archive the artifacts
-        //
-        //archiveArtifacts artifacts: 'target/**', fingerprint: true, onlyIfSuccessful: true
-        //
-        // Also via stash. If this works, the archiveArtifacts line abpve is not needed
-        //
-        stash includes: 'target/**', name: 'fibo-publish-script'
-
-    }
+    },
     //
     // Build the artifacts that that need the nomagic installation
     //
-    node('nomagic') {
-        withEnv(['DISPLAY=localhost:10.0']) {
+    "nomagic" : {
+        node('nomagic') {
+            echo "Executing generate script on the nomagic box"
             sh """#!/bin/bash -x
-              ./home/ec2-user/dev.sh
-              ./home/ec2-user/prod.sh
+                unset DISPLAY
+
+                if ! cd /home/ec2-user/MagicDraw ; then
+                    echo "Could not find MagicDraw directory"
+                    exit 1
+                fi
+                if ! cd ./plugins/com.nomagic.magicdraw.reportwizard ; then
+                    echo "Could not find MagicDraw report wizard"
+                    exit 1
+                fi
+
+                ./generate.sh \
+                    -login "EDMCJenkins" \
+                    -server "twc184.nomagic.com:3579" \
+                    -password "hZ7LQF_kmFV-6N2E" \
+                    -project "FIBO-Master" \
+                    -template "Natural Language Glossary for FIBO versions" \
+                    -package "Release;Provisional;Informative" \
+                    -output "${WORKSPACE}/development.html" \
+                    -servertype "twcloud" \
+                    -report "Development"
+
+                ./generate.sh \
+                    -login "EDMCJenkins" \
+                    -server "twc184.nomagic.com:3579" \
+                    -password "hZ7LQF_kmFV-6N2E" \
+                    -project "FIBO-Master" \
+                    -template "Natural Language Glossary for FIBO versions" \
+                    -package "Release" \
+                    -output "${WORKSPACE}/production.html" \
+                    -servertype "twcloud" \
+                    -report "Production"
+
             """
+            stash includes: '*.html', name: 'nomagic-output'
         }
-        sh 'cp /home/ec2-user/MagicDraw/plugins/com.nomagic.magicdraw.reportwizard/*.html .'
-        stash includes: '*.html', name: 'nomagic-output'
     }
 }
 
@@ -127,7 +159,7 @@ stage('Publish') {
             sh 'ls -al'
             sh 'find .'
             sh 'cp -r generated fibo'
-            sh 'cp *.html fibo/generated/glossary'
+            sh 'cp *.html fibo/glossary'
             sh 'ls -al /mnt/jenkins-disk/spec.edmcouncil.org/'
             sh 'cp -vr . /mnt/jenkins-disk/spec.edmcouncil.org/'
         }
